config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  resources :posts, except: :destroy do
    resources :comments, only: :create
  end

  resources :users, only: [:new, :create, :edit, :update, :show]

  post '/posts/:id/vote', to: 'posts#vote', as: :vote_post
  post '/comments/:id/vote', to: 'comments#vote', as: :vote_comment

  get 'register', to: 'users#new'
  get 'users/profile', to: 'users#show'
  resources :categories, only: [:new, :create, :show]

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
end

app/models/category.rb
class Category < ActiveRecord::Base
  include Sluggable

  belongs_to :user
  has_many :post_categories
  has_many :posts, through: :post_categories

  validates :category, presence: true, uniqueness: true, length: {minimum: 3}

  sluggable_column :category
  before_save :generate_slug

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
  has_many :votes, as: :votable
  validates :body, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  include Sluggable

  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  has_many :comments
  has_many :post_categories
  has_many :categories, through: :post_categories
  has_many :votes, as: :votable

  validates :title, presence: true, uniqueness: true, length: {minimum: 5}
  validates :description, presence: true
  validates :url, format: {with: /\A(http:|https:)\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(([0-9]{1,5})?\/.*)?\z/ix}

  sluggable_column :title
  before_save :generate_slug
end

app/models/post_category.rb
class PostCategory < ActiveRecord::Base
  belongs_to :category
  belongs_to :post
end

app/models/user.rb
class User < ActiveRecord::Base
  include Sluggable

  has_many :comments
  has_many :posts
  has_many :votes

  has_secure_password validations: false
  validates :username, presence: true, uniqueness: true
  validates :password, presence: true, on: :create, length: {minimum: 3}

  sluggable_column :username
  before_save :generate_slug

  def admin?
    self.role == "admin"
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :creator, class_name: 'User', foreign_key: 'user_id'
  belongs_to :votable, polymorphic: true

  # pass an array of columns to scope
  # see: http://api.rubyonrails.org/classes/ActiveRecord/Validations/ClassMethods.html#method-i-validates_uniqueness_of
  validates_uniqueness_of :creator, scope: [:votable_id, :votable_type]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?, :total_votes

  def current_user
    current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def total_votes(votable)
    votes = votable.votes
    votes.select { |v| v if v.vote }.count - votes.select { |v| v if not v.vote }.count
    end

  def user_hasnt_voted(votable)
    votable.votes.each do |vote|
      if vote.user_id == current_user[:id]
        return false
      end
      true
    end
  end

  def require_admin
    access_denied unless logged_in? and current_user.admin?
  end

  def access_denied
    flash[:error] = "You don't have the access priveleges to do that."
    redirect_to root_path
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, only: [:new, :create]

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    @category[:category].capitalize!

    if @category.save
      flash[:notice] = "Your new category has been created."
      redirect_to posts_path
    else
      render :new
    end
  end

  def show
    @category = Category.find_by slug: params[:id]
  end

  private

  def category_params
    params.require(:category).permit(:category)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    if not logged_in?
      flash[:error] = "You must be logged in to leave a comment."
      redirect_to post_path(params[:post_id])
    else
      @post = Post.find_by slug: params[:post_id]
      @comment = @post.comments.build(params.require(:comment).permit(:body))
      ## prev line equivalent to:
      #@comment = Comment.new(params.require(:comment).permit(:body))
      #@comment.post = @post
      @comment.user_id = current_user.id
      if @comment.save
        flash[:notice] = "Your comment has been saved."
        redirect_to post_path(@post)
      else
        render '/posts/show'
      end
    end
  end

  def vote
    @comment = Comment.find_by id: params[:id]
    @vote = Vote.create(user_id: current_user.id, vote: params[:vote], votable: @comment)

    respond_to do |format|
      format.html do
        if @vote.valid?
          flash[:notice] = "Your vote has been counted."
        else
          flash[:notice] = "You cannot vote twice on a comment."
        end
        redirect_to post_path(@comment.post.id)
      end
      format.js
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :vote]

  def index
    @posts = Post.all
  end

  def show
    @comment = Comment.new
  end

  def new
    if not current_user
      flash[:error] = "You must log in or register to create a new post."
      redirect_to posts_path
    else
      @post = Post.new
    end
  end

  def vote
    @vote = Vote.create(user_id: current_user.id, vote: params[:vote], votable: @post)
    respond_to do |format|
      format.html do
        if @vote.valid?
          flash[:notice] = "Your vote has been counted."
        else
          flash[:notice] = "You cannot vote twice on one post."
        end
        redirect_to posts_path
      end
      # by default this will try to render a vote.js.erb file, so we
      # can leave off the block if that is what we want.
      format.js
    end
  end

  def create
    @post = Post.new(post_params)
    @post.creator = current_user

    if @post.save
      flash[:notice] = "Your post was created."
      redirect_to posts_path
    else
      render :new
    end
  end

  def edit
    post = Post.find_by slug: params[:id]
    if !logged_in? || post.creator.id != current_user[:id] and !current_user.admin?
      flash[:error] = "You must be logged in and either the author of a post or an admin in order to edit."
      redirect_to post_path
    end
  end

  def update
    if @post.update(post_params) &&
      flash[:notice] = "Your post has been updated."
      redirect_to posts_path
    else
      render :edit
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :url, :description, category_ids: [])
      end

  def set_post
    @post = Post.find_by slug: params[:id]
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by username: params[:username]
    if user && user.authenticate(params[:password])
      flash[:notice] = "Welcome #{params[:username]}"
      session[:user_id] = user.id
      redirect_to posts_path
    else
      flash[:error] = "Username or password was not recognized. Try again or register."
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You're logged out. Bye!"
    redirect_to posts_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if User.count == 0
      @user.role = "admin"
    end

    if @user.save
      flash[:notice] = "Welcome #{@user.username}"
      session[:user_id] = @user.id
      redirect_to posts_path
    else
      render :new
    end
  end

  def show
    @user = current_user
  end

  def edit
    @user = current_user
  end

  def update
    user = current_user
    if user.update(user_params)
      flash[:notice] = "Your profile has been updated."
      redirect_to users_profile_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :bio, :time_zone)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def readable_time(time)
    if logged_in? && !current_user.time_zone.blank?
      time = time.in_time_zone(current_user.time_zone)
    end
    time.strftime("%m/%d/%Y %l:%M%P %Z")
  end
end

app/views/categories/_category.html.erb
<span class="badge"><%= link_to category.category, category_path(category) %></span>

app/views/categories/new.html.erb
<%= render "shared/content_title", title: "Add a Category" %>

<%= render partial: "shared/error", object: @category %>

<%= form_for @category do |f| %>
  <%= f.label :category %>
  <%= f.text_field :category %>
  <br/>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/categories/show.html.erb
<% all_posts = link_to("All Posts", posts_path) %>

<%= render 'shared/content_title', title: "#{all_posts} &raquo; #{@category.category}".html_safe %>

<%= render partial: 'shared/category_index_list', object: @category.posts %>

app/views/comments/vote.js.erb
<% if @vote.valid? %>
  $("#comment_<%= @comment.id %>_votes").html("<%= total_votes(@comment) %>")
<% else %>
  alert("You can't vote twice per comment")
<% end %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav">
  <li>
    <%= link_to "PostIt!", root_path, :class => 'brand' %>
  </li>
</ul>

<ul class='inline'>
  <div class="btn-group nav-item">
    <%= link_to '#', class: 'btn btn-small dropdown-toggle', 'data-toggle' => 'dropdown' do %>
      Categories <span class='caret'></span>
    <% end %>
    <ul class='dropdown-menu'>

      <% Category.all.each do |category| %>
        <li>
	  <%= link_to category.category, category_path(category) %>
        </li>
      <% end %>

      <% if logged_in? and current_user.admin?%>
        <li class='divider'></li>
        <li>
	  <%= link_to(new_category_path) do %>
	    <i class="icon-plus"></i>
            New Category
	  <% end %>
      <% end %>
        </li>
    </ul>
  </div>


  <% if logged_in? %>
    <%= link_to "New Post", new_post_path, class: 'btn btn-small' %>

    <div class="btn-group nav-item">
      <%= link_to '#', class: 'btn btn-small dropdown-toggle', 'data-toggle' => 'dropdown' do %>
        <%=current_user.username%> <span class='caret'></span>
      <% end %>
      <ul class='dropdown-menu'>

        <li>
	  <%= link_to(edit_user_path(current_user[:id])) do %>
            <i class='icon-pencil'></i>
	    edit profile
	  <% end %>
        </li>

        <li>
	  <%= link_to(users_profile_path) do %>
            <i class='icon-user'></i>
	    view profile
	  <% end %>
        </li>

        <li>
	  <%= link_to(logout_path) do %>
            <i class='icon-circle-arrow-left'></i>
	    logout
	  <% end %>
        </li>

      </ul>

  <% else %>
      <%= link_to "Login", login_path, class: 'btn btn-small btn-success' %>
      <%= link_to "Register", register_path, class: 'btn btn-small btn-success' %>
  <% end %>



</ul>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Postit</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header>
      <div class="navbar navbar-inverse">
        <div class="navbar-inner">
          <div class="container">
            <%= render 'layouts/navigation' %>
          </div>
        </div>
      </div>
    </header>
    <div id="main" role="main">
      <div class="container">
         <div class="row">
          <div class="span12">
            <%= render 'layouts/messages' %>
            <%= yield %>
          </div>
        </div>
        <footer>
        </footer>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/posts/_form.html.erb
<%= render partial: "shared/error", object: @post %>

<%= form_for @post do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :url %>
  <%= f.text_field :url %>

  <%= f.label :description %>
  <%= f.text_area :description, rows: 5, class: "span11" %>

  <div class="control-group">
    <%= f.label "Categories" %>
    <%= f.collection_check_boxes :category_ids, Category.all, :id, :category do |cb| %>
      <%= cb.label(class: "checkbox inline") { cb.check_box(class: "checkbox") + cb.text} %>
    <% end %>
  </div>


  <br/>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/posts/edit.html.erb
<%= render 'shared/content_title', title: "Edit your post" %>

<%= render "form" %>

app/views/posts/index.html.erb
<%= render 'shared/content_title', title: "All Posts" %>

<%= render partial: 'shared/category_index_list', object: @posts %>

app/views/posts/new.html.erb
<%= render 'shared/content_title', title: "Create a new Post" %>

<%= render "form" %>

app/views/posts/show.html.erb
<p class="pull-right">
  <%= link_to("Edit Post", edit_post_path(@post)) %>
<p>

<p>
  <%= render @post.categories %>
</p>

<%= render 'shared/content_title', title: @post.title %>

<p>
  <%= @post.description %>
</p>

<hr/>

<div class="well">
<%= form_for [@post, @comment] do |f| %>
  <%= render partial: "shared/error", object: @comment %>
  <%= f.label :body, 'Leave a comment (you must be logged in)' %>
  <%= f.text_area :body, rows: 4, class: "span5", disabled: (not logged_in?) %>
  <br/>
  <%= f.submit class: "btn btn-primary", disabled: (not logged_in?) %>
<% end %>
</div>

<%= render 'shared/content_title', title: "Previous comments" %>

<% @post.comments.each do |comment| %>
  <%= render '/shared/comments', comment: comment %>
<% end %>

app/views/posts/update.html.erb
<%= render 'shared/content_title', title: "Update your post." %>

<%= render "form" %>

app/views/posts/vote.js.erb
<% if @vote.valid? %>
   $("#post_<%= @post.slug %>_votes").html("<%= total_votes(@post) %>")
<% else %>
   alert("You can vote only once per post!");
<% end %>

app/views/shared/_category_index_list.html.erb
<% category_index_list.each do |post| %>
  <%= render '/shared/posts', post: post %>
<% end %>

app/views/shared/_comments.html.erb
<% show_post ||= false %>

<div class="row">
  <div class="span0">

    <%= link_to vote_comment_path(comment, vote: true), method: "post", remote: true do %>
      <i class="icon-thumbs-up"></i>
    <% end %>
    <br/>

    <span id="comment_<%= comment.id %>_votes"><%= total_votes(comment) %></span>
    <br/>
    <%= link_to vote_comment_path(comment, vote: false), method: "post", remote: true do %>
      <i class="icon-thumbs-down"></i>
    <% end %>
  </div>

  <div class="span8">
    <em>"<%= comment.body %>"</em>
    <% if show_post %>
      on <%= link_to comment.post.title, post_path(comment.post) %>
    <% end %>
    <br/>
    <span class="quiet">By </span><%= link_to comment.user.username, '' %>
    <span class="quiet"><small>at <%= comment.created_at %></small></span>
  </div>
  <hr/>
</div>

app/views/shared/_content_title.html.erb
<p class="lead">
  <%= title %>
  <hr/>
</p>

app/views/shared/_error.html.erb
<% if error.errors.any? %>
  <div class="row">
    <div class="alert alert-error span8">
      <h5>Oopsie! Your submission hit a bump.</h5>
      <% error.errors.full_messages.each do |msg| %>
      <ul>
	<li><%= msg %></li>
      </ul>
      <% end %>
    </div>
  </div>
<% end %>

app/views/shared/_posts.html.erb
<% if post.url == "" or !post.url %>
  <% post_url = "self" %>
<% else %>
  <% post_url = post.url %>
<% end %>

<div class="row">
  <div class="span0">
    <%= link_to vote_post_path(post[:id], vote: true), method: "post", remote:true do %>
      <i class="icon-thumbs-up"></i>
    <% end %>
    <br/>

    <span id="post_<%=post.slug%>_votes"><%= total_votes(post) %></span>

    <br/>
    <%= link_to vote_post_path(post[:id], vote: false), method: "post", remote: true do %>
      <i class="icon-thumbs-down"></i>
    <% end %>
  </div>

  <div>
    <ul class="inline">
      <li id="title"><%= link_to post.title, post_path(post) %></li>
      <% if !post.url or post.url.length > 4 %>
        <li> <%= link_to "(visit)", post.url %> </li>
      <% else %>
        <li> <%= link_to "(self)", post_path(post) %> </li>
      <% end %>
      <li class="pull-right">(<%= link_to("#{post.comments.size} comments", post_path(post)) %>)<li>

    </ul>

    <ul class='inline'>
      <li>
	<span class="quiet">Posted by </span> <%= link_to "#{post.creator.username}", user_path(post.creator) %>
	<span class="quiet"><small>on <%= readable_time(post.created_at) %></small></span>
      </li>
      <li class="pull-right"><%= render post.categories %></li>
    </ul>
  </div>
  <hr class="post_sep" />
</div>

app/views/users/_form.html.erb
<%= render partial: "shared/error", object: @user %>

<%= form_for @user do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.label :time_zone %>
  <%= f.time_zone_select :time_zone, ActiveSupport::TimeZone.us_zones, default: Time.zone.name %>
  <br/>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/users/edit.html.erb
<%= render 'shared/content_title', title: "Edit your profile" %>

<%= form_for @user do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>
  <%= f.label :bio %>
  <%= f.text_area :bio %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.label :time_zone %>
  <%= f.time_zone_select :time_zone, ActiveSupport::TimeZone.us_zones %>
  </br>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/users/new.html.erb
<%= render "shared/content_title", title: "Sign up for Postit here." %>

<%= render "form" %>

app/views/users/show.html.erb
<%= render 'shared/content_title', title: "#{@user.username}'s Profile" %>

<div class="well" %>
  <dl class="dl-horizontal">
    <dt>User name</dt>
    <dd><p><%= @user.username %></p></dd>
    <dt>Time Zone</dt>
    <dd><p><%= @user.time_zone %></p></dd>
    <dt>Bio</dt>
    <dd><p><%= @user.bio %></p></dd>
  </dl>
</div>

<h5><%= @user.username %>'s activity </h5>

<ul class="nav nav-tabs">
  <li class='<%= 'active' if params[:tab].nil? %>'>
    <%= link_to "Posts (#{@user.posts.size})", user_path(@user) %>
  </li>
  <li class='<%= 'active' if params[:tab] == 'comments' %>' >
    <%= link_to "Comments (#{@user.comments.size})", user_path(@user, tab: "comments") %>
  </li>
</ul>

<% if params[:tab].nil? %>

  <% @user.posts.each do |post| %>
   <%= render '/shared/posts', post: post %>
  <% end %>

<% else %>

  <% @user.comments.each do |comment| %>
    <%= render '/shared/comments', comment: comment, show_post: true %>
  <% end %>

<% end %>